pipeline {
    agent none {
        stages {
            stage('checkout') {
                steps {
                    sh 'yum install -y python3'
                }
            }
            stage('test') {
                steps {
                    sh 'python3 --version'
                }
            }
        }
    }
}
