pipeline{
    agenr none{
        stages{
            stage ('checkout'){
                steps{
                    sh 'yum install python3'
                }
            }
            stage ('test'){
                steps{
                    sh 'python3 --version'
                }
            }
        }
    }
}